# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Uncategorized', max_length=255, verbose_name='Category Name')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ver1.Category')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Product Name')),
                ('size', models.CharField(max_length=1, verbose_name='Product Size')),
                ('color', models.CharField(max_length=250, null=True, verbose_name='Product Color')),
                ('price', models.IntegerField(default=0, verbose_name='Product Price')),
                ('category', models.ManyToManyField(to='ver1.Category')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
