# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=255, unique=True, verbose_name='Category Name'),
        ),
    ]
