# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver1', '0004_auto_20160522_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_parent_+', to='ver1.Category'),
        ),
    ]
