# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ver1', '0006_auto_20160522_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size'},
        ),
    ]
