# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ver1', '0007_auto_20160522_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_set', to='ver1.Category'),
        ),
    ]
